// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-sk9D6uwRsBUfMkJQIWxA2FFgclg4biM',
    appId: '1:122736298446:web:2d25433b7371e52cf5839f',
    messagingSenderId: '122736298446',
    projectId: 'equa-2c7c7',
    authDomain: 'equa-2c7c7.firebaseapp.com',
    storageBucket: 'equa-2c7c7.firebasestorage.app',
    measurementId: 'G-VHEBMHH5QE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2kw2_Nsm0m-usoPn6OF7n5ISSPN4lXOg',
    appId: '1:122736298446:android:36d484432683de48f5839f',
    messagingSenderId: '122736298446',
    projectId: 'equa-2c7c7',
    storageBucket: 'equa-2c7c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxAS7SBRa5qe3ixw3v_USWoYuG5e57I9s',
    appId: '1:122736298446:ios:a4dc51d1aa6dc2bdf5839f',
    messagingSenderId: '122736298446',
    projectId: 'equa-2c7c7',
    storageBucket: 'equa-2c7c7.firebasestorage.app',
    iosBundleId: 'com.example.equa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxAS7SBRa5qe3ixw3v_USWoYuG5e57I9s',
    appId: '1:122736298446:ios:a4dc51d1aa6dc2bdf5839f',
    messagingSenderId: '122736298446',
    projectId: 'equa-2c7c7',
    storageBucket: 'equa-2c7c7.firebasestorage.app',
    iosBundleId: 'com.example.equa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-sk9D6uwRsBUfMkJQIWxA2FFgclg4biM',
    appId: '1:122736298446:web:d727e990c5f60a88f5839f',
    messagingSenderId: '122736298446',
    projectId: 'equa-2c7c7',
    authDomain: 'equa-2c7c7.firebaseapp.com',
    storageBucket: 'equa-2c7c7.firebasestorage.app',
    measurementId: 'G-RH45NSYPSW',
  );
}
